### ISSUE TITLE
Show worflow info, not only python info.

### ISSUE THREAD

**Issue by adiroiban** [twisted/python-info-action#5]
Klein has this extra info - https://github.com/twisted/klein/blob/4e6bb27536d7437ac9eecab76b9c00bbd9ee103c/.github/workflows/cicd.yml#L18

Once this is done, use it in Klein  https://github.com/twisted/klein/issues/458

**Comment by altendky** [comment]
Hey fun, I just used this tonight when trying to find `github.event.schedule` to identify a scheduled build...  nice quick payback.  (though it turns out just using the upload token might suffice to address the actual issue)
